---
- name: Download Composer
  become: yes
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer

- name: Install Composer
  become: yes
  shell: cat /tmp/installer | php -- --install-dir={{ composer_path }} --filename=composer
  args:
    creates: "{{ composer_path }}/composer"