---
- name: Create Composer download folder
  become: yes
  file:
   path: "{{ composer_install_path }}"
   state: directory
   owner: root
   group: root
   mode: 0755

- name: Download Composer
  become: yes
  get_url:
    url: https://getcomposer.org/installer
    dest: "{{ composer_install_path }}/installer"
    mode: 0755

- name: Install Composer
  become: yes
  command: ./installer
  args:
    chdir: "{{ composer_install_path }}"
    creates: "{{ composer_install_path }}/composer.phar"

- name: Copy composer.phar to its final location
  become: yes
  copy:
    src: "{{ composer_install_path }}/composer.phar"
    dest: "{{ composer_path }}/composer"
    owner: root
    group: root
    mode: 0755

- name: Clean Composer download folder
  become: yes
  file:
   path: "{{ composer_install_path }}"
   state: absent