---
- name: Check if php is installed
  command: php --version
  register: composer_php_check

- name: Composer | Install Composer
  sudo: yes
  shell: "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
  args:
    creates: /usr/local/bin/composer
  when: composer_php_check.stdout.find('not installed') == -1