---
- name: Check if Composer is installed
  command: composer_php_check.stdout.find('not installed') == -1
  changed_when: false
  register: composer_is_installed

- include: install.yml
  when: not composer_is_installed

- name: Recheck if Composer is installed
  command: composer_php_check.stdout.find('not installed') == -1
  changed_when: false
  register: composer_is_installed

- include: update.yml
  when: not composer_is_installed