---
- name: Get stat of Composer file
  stat:
    path: "{{ composer_path }}/composer"
  register: composer_stat

- name: Get date for Composer update
  shell: >
    date --date='{{ composer_update_day }} days ago' +'%s'
  register: composer_last_update
  changed_when: False

- name: Update Composer if necessary
  become: yes
  shell: >
    {{ composer_path }}/composer selfupdate
  when: composer_last_update.stdout|int > composer_stat.stat.mtime|int